const db = require('./db');

const fakulteler = [
  "Açık ve Uzaktan Öğretim Fakültesi",
  "Diş Hekimliği Fakültesi",
  "Eczacılık Fakültesi",
  "Edebiyat Fakültesi",
  "Fen Fakültesi",
  "Güzel Sanatlar Fakültesi",
  "Hemşirelik Fakültesi",
  "Hukuk Fakülesi",
  "İktisadi ve İdari Bilimler Fakültesi",
  "İlahiyat Fakültesi",
  "İletişim Fakültesi",
  "Kazım Karabekir Eğitim Fakültesi",
  "Mimarlık ve Tasarım Fakültesi",
  "Mühendislik Fakültesi",
  "Oltu Beşeri ve Sosyal Bilimler Fakültesi",
  "Sağlık Bilimleri Fakültesi",
  "Spor Bilimleri Fakültesi",
  "Su Ürünleri Fakültesi",
  "Tıp Fakültesi",
  "Turizm Fakültesi",
  "Uygulamalı Bilimler Fakültesi",
  "Veteriner Fakültesi",
  "Ziraat Fakültesi"
];

async function setup() {
  try {
    await db.schema.dropTableIfExists('akademik_danismanlar');

    await db.schema.createTable('akademik_danismanlar', table => {
      table.increments('id').primary();
      table.string('isim');
      table.string('unvan');
      table.string('fakulte');
      table.string('eposta');
      table.string('ofis_saati');
      table.datetime('eklenmis_veri');
    });

    const danismanlar = [
    {
      isim: 'Ayşe Özdemir',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Açık ve Uzaktan Öğretim Fakültesi',
      eposta: 'ayseozdemir@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Fatma Koç',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Açık ve Uzaktan Öğretim Fakültesi',
      eposta: 'fatmakoc@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Hüseyin Arslan',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Açık ve Uzaktan Öğretim Fakültesi',
      eposta: 'huseyinarslan@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Hatice Doğan',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Açık ve Uzaktan Öğretim Fakültesi',
      eposta: 'haticedogan@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Merve Özkan',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Açık ve Uzaktan Öğretim Fakültesi',
      eposta: 'merveozkan@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Esra Yıldız',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Diş Hekimliği Fakültesi',
      eposta: 'esrayildiz@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Melis Taş',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Diş Hekimliği Fakültesi',
      eposta: 'melistas@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Şeyma Güneş',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Diş Hekimliği Fakültesi',
      eposta: 'seymagunes@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Hasan Aksoy',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Diş Hekimliği Fakültesi',
      eposta: 'hasankasoy@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Büşra Öztürk',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Diş Hekimliği Fakültesi',
      eposta: 'busraozturk@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Ahmet Yılmaz',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Edebiyat Fakültesi',
      eposta: 'ahmetyılmaz@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Zeynep Kaya',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Edebiyat Fakültesi',
      eposta: 'zeynepkaya@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Mehmet Demir',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Edebiyat Fakültesi',
      eposta: 'mehmetdemir@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Elif Aydın',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Edebiyat Fakültesi',
      eposta: 'elifaydin@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Mustafa Şahin',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Edebiyat Fakültesi',
      eposta: 'mustafasahin@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Ebru Uçar',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Eczacılık Fakültesi',
      eposta: 'ebruucar@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Serkan Çetin',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Eczacılık Fakültesi',
      eposta: 'serkancetin@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Duygu Kıran',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Eczacılık Fakültesi',
      eposta: 'duygukiran@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Gül Duran',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Eczacılık Fakültesi',
      eposta: 'gulduran@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Uğur Yiğit',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Eczacılık Fakültesi',
      eposta: 'uguryigit@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Levent Cemil',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Fen Fakültesi',
      eposta: 'leventcemil@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Funda Güler',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Fen Fakültesi',
      eposta: 'fundaguler@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Tuğba Karataş',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Fen Fakültesi',
      eposta: 'tugbakaratas@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Hande Akın',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Fen Fakültesi',
      eposta: 'handeakin@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Erdem Elmas',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Fen Fakültesi',
      eposta: 'erdemelmas@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Pınar Aksu',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Güzel Sanatlar Fakültesi',
      eposta: 'pinaraksu@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Sevgi Özer',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Güzel Sanatlar Fakültesi',
      eposta: 'sevgiozer@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Kübra Taşkın',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Güzel Sanatlar Fakültesi',
      eposta: 'kubrataskin@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Simge Sönmez',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Güzel Sanatlar Fakültesi',
      eposta: 'simgesonmez@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Meltem Aksoy',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Güzel Sanatlar Fakültesi',
      eposta: 'meltemaksoy@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Sibel Turan',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Hemşirelik Fakültesi',
      eposta: 'sibelturan@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Betül Altun',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Hemşirelik Fakültesi',
      eposta: 'betulaltun@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Şirin Yıldırım',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Hemşirelik Fakültesi',
      eposta: 'sirinyildirim@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Koray Işık',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Hemşirelik Fakültesi',
      eposta: 'korayisik@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'İlayda Sevim',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Hemşirelik Fakültesi',
      eposta: 'ilaydasevim@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Taha Şentürk',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Hukuk Fakültesi',
      eposta: 'tahasenturk@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Yaren Gültekin',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Hukuk Fakültesi',
      eposta: 'yarengultekin@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Cem Baran',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Hukuk Fakültesi',
      eposta: 'cembaran@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Defne Köse',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Hukuk Fakültesi',
      eposta: 'defnekose@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Hilal Korkut',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Hukuk Fakültesi',
      eposta: 'hilalkorkut@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Zehra Karagöz',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İktisadi ve İdari Bilimler Fakültesi',
      eposta: 'zehrakaragoz@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Gözde Uysal',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İktisadi ve İdari Bilimler Fakültesi',
      eposta: 'gozdeuysal@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Harun Gür',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İktisadi ve İdari Bilimler Fakültesi',
      eposta: 'harungur@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Asude Vural',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İktisadi ve İdari Bilimler Fakültesi',
      eposta: 'asudevural@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Sena Başaran',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İktisadi ve İdari Bilimler Fakültesii',
      eposta: 'senabasaran@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'İrem Solmaz',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İlahiyat Fakültesi',
      eposta: 'iremsolmaz@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Arzu Bilgin',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İlahiyat Fakültesi',
      eposta: 'arzubilgin@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Yasin Albayrak',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İlahiyat Fakültesi',
      eposta: 'yasinalbayrak@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Melek Yurt',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İlahiyat Fakültesi',
      eposta: 'melekyurt@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Nur Yiğit',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İlahiyat Fakültesi',
      eposta: 'nuryigit@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Melek Ahıskalı',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İletişim Fakültesi',
      eposta: 'melekahiskali@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Mine Öztürk',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İletişim Fakültesi',
      eposta: 'mineozturk@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Yelda Karaman',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İletişim Fakültesi',
      eposta: 'yeldakaraman@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Ece Barut',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İletişim Fakültesi',
      eposta: 'ecebarut@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Sezgin Akyüz',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'İletişim Fakültesi',
      eposta: 'sezginakyuz@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Orhan Tamer',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Kazım Karabekir Eğitim Fakültesi',
      eposta: 'orhantemel@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Sevgi Özer',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Kazım Karabekir Eğitim Fakültesi',
      eposta: 'sevgiozer@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Sevil Aydoğdu',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Kazım Karabekir Eğitim Fakültesi',
      eposta: 'sevilaydogdu@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Gaye Temel',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Kazım Karabekir Eğitim Fakültesi',
      eposta: 'gayetemel@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Lale Koçak',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Kazım Karabekir Eğitim Fakültesi',
      eposta: 'lalekocak@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Asya Soylu',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Mimarlık ve Tasarım Fakültesi',
      eposta: 'asyasoylu@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Eylül Yıldırım',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Mimarlık ve Tasarım Fakültesi',
      eposta: 'eylulyildirim@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Kerem Özgür',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Mimarlık ve Tasarım Fakültesi',
      eposta: 'keremozgur@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Nehir Gülsoy',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Mimarlık ve Tasarım Fakültesi',
      eposta: 'nehirgulsoy@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Kıvanç Gürel',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Mimarlık ve Tasarım Fakültesi',
      eposta: 'kivancgurel@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Zeynep Odabaş',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Mühendislik Fakültesi',
      eposta: 'zeynepodabas@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Emre Güngör',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Mühendislik Fakültesi',
      eposta: 'emregungor@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Ata Güngör',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Mühendislik Fakültesi',
      eposta: 'atagungor@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Alparslan Güngör',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Mühendislik Fakültesi',
      eposta: 'alparslangungor@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'İpek Yalçın',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Mühendislik Fakültesi',
      eposta: 'ipekyalcin@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Aybike Gökçen',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Oltu Beşeri ve Sosyal Bilimler Fakültesi',
      eposta: 'aybikegokcen@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Cansu Eren',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Oltu Beşeri ve Sosyal Bilimler Fakültesi',
      eposta: 'cansueren@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Ekin Su',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Oltu Beşeri ve Sosyal Bilimler Fakültesi',
      eposta: 'ekinsu@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Gökçe Aydoğdu',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Sağlık Bilimleri Fakültesi',
      eposta: 'gokceaydogdu@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Leman Doğan',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Sağlık Bilimleri Fakültesi',
      eposta: 'lemandogan@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Ecrin Taşcı',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Sağlık Bilimleri Fakültesi',
      eposta: 'ecrintasci@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Emir Yavuz',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Sağlık Bilimleri Fakültesi',
      eposta: 'emiryavuz@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Derya Üstün',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Sağlık Bilimleri Fakültesi',
      eposta: 'deryaustun@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Zümra Gülce',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Spor Bilimleri Fakültesi',
      eposta: 'zumragulce@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Uğur Yiğit',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Spor Bilimleri Fakültesi',
      eposta: 'uguryigit@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Esila Demirci',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Su Ürünleri Fakültesi',
      eposta: 'esilademirci@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Perihan Toprak',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Su Ürünleri Fakültesi',
      eposta: 'perihantoprak@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Tuğba Çolakoğlu',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Tıp Fakültesi',
      eposta: 'tugbacolakoglu@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Betül Sena Çağın',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Tıp Fakültesi',
      eposta: 'betulsenacagin@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Şevval Korkmaz',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Tıp Fakültesi',
      eposta: 'sevvalkorkmaz@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Pınar Aksu',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Tıp Fakültesi',
      eposta: 'pinaraksu@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Sevgi Aydınlık',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Tıp Fakültesi',
      eposta: 'sevgiaydinlik@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Hakkı Arısoy',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Turizm Fakültesi',
      eposta: 'hakkiarisoy@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Elçin Tanrıkulu',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Turizm Fakültesi',
      eposta: 'elcintanrikulu@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Berrak Dalkılıç',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Turizm Fakültesi',
      eposta: 'berrakdalkilic@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Melike Ertem',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Uygulamalı Bilimler Fakültesi',
      eposta: 'melikeertem@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Betül Kılıç',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Veteriner Fakültesi',
      eposta: 'betulkilic@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
    {
      isim: 'Lale Özçelik',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Veteriner Fakültesi',
      eposta: 'laleozcelik@edu.tr',
      ofis_saati: 'Salı 15:00',
    },
    {
      isim: 'Aylin Günel',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Veteriner Fakültesi',
      eposta: 'aylingunel@edu.tr',
      ofis_saati: 'Perşembe 16:00',
    },
    {
      isim: 'Tuana Sağlam',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Veteriner Fakültesi',
      eposta: 'tuanasaglam@edu.tr',
      ofis_saati: 'Cuma 11:00',
    },
    {
      isim: 'Ömer Şentürk',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Ziraat Fakültesi',
      eposta: 'omersenturk@edu.tr',
      ofis_saati: 'Çarşamba 17:00',
    },
    {
      isim: 'Yaren Gül',
      unvan: 'Araştırma Görevlisi',
      fakulte: 'Ziraat Fakültesi',
      eposta: 'yarengul@edu.tr',
      ofis_saati: 'Pazartesi 09:00',
    },
   ].map(item => ({
     ...item,
     eklenmis_veri: new Date()
   }));
    await db('akademik_danismanlar').insert(danismanlar);
    console.log('✅ Akademik danışmanlar başarıyla eklendi.');
    process.exit();
  } catch (err) {
    console.error('❌ Hata oluştu:', err);
    process.exit(1);
  }
}

setup();
